version: "3.8"

services:
  ticket:
    image: souni/ticket
    ports:
      - "8085:8085"
    networks:
      - souni-network
    depends_on:
      - config
      - eureuka
      - db


    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/voyageAgency?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root
  db:
    image: mysql:8
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: voyageAgency
    ports:
      - "3306:3306"
    networks:
      - souni-network

  config:
    image: souni/serverconfig
    ports:
      - "8087:8087"
    networks:
      - souni-network

  eureuka:
    image: souni/eureuka
    ports:
      - "8761:8761"
    networks:
      - souni-network    
  
  
networks:
  souni-network: