version: "3.9"

services:
 
 eurekaserver:
   build: C:\Users\yariahi\Desktop\micro-service\eureuka
   container_name: eureka
   image: eureka-images
   networks:
      - eureka-server
   ports:
    - "8761:8761"

 zuul-gateway:
   build: C:\Users\yariahi\Desktop\micro-service\Zuul-Gateway\Zuul-Gateway
  #  network_mode: host 
   image: zuul-images
   ports:
   - "8762:8762"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

 microservice-voyage:
   build: C:\Users\yariahi\Desktop\micro-service\Voyage
  #  network_mode: host 
   image: voyage-images
   ports:
   - "8085:8085"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

 microservice-client:
   build: C:\Users\yariahi\Desktop\micro-service\Client
  #  network_mode: host 
   image: client-images
   ports:
   - "8090:8090"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

 mysql-db:
    image: mysql:latest
    networks:
      - mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=entreprise
  
 microservice-entreprise:
   build: C:\Users\yariahi\Desktop\micro-service\Entreprise
  #  network_mode: host 
   image: entreprise-images
   ports:
   - "8099:8099"
   networks:
      - eureka-server
      - mysql-db
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/entreprise
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=
   depends_on:
     - eurekaserver
     - mysql-db

networks:
  eureka-server:
    name: eureka-server
    driver: bridge
  mysql-db:
    name: mysql-db
    driver: bridge
