version: "3.9"

services:
 
 eurekaserver:
   build: C:\Users\yariahi\Desktop\micro-service\eureuka
   container_name: eureka
   image: eureka-images
   networks:
      - eureka-server
   ports:
    - "8761:8761"


  microservice-voyage:
   build: C:\Users\SPIRIT\Videos\microService\Voyage
  #  network_mode: host 
   image: voyage-images
   ports:
   - "8085:8085"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

 microservice-client:
   build: C:\Users\SPIRIT\Videos\microService\Client
  #  network_mode: host 
   image: client-images
   ports:
   - "8090:8090"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

 zuul-gateway:
   build: C:\Users\SPIRIT\Videos\microService\Zuul-Gateway\Zuul-Gateway
  #  network_mode: host 
   image: zuul-images
   ports:
   - "8762:8762"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver
     
 microservice-entreprise:
   build: C:\Users\yariahi\Desktop\Microservice\EntrepriseServer
  #  network_mode: host 
   image: entreprise-images
   ports:
   - "8099:8099"
   networks:
      - eureka-server
   environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
   depends_on:
     - eurekaserver

networks:
  eureka-server:
    name: eureka-server
    driver: bridge


